### PR TITLE
Fix for failing duration selector on live streams...

### PR DESCRIPTION
**Pull request by RunninglVlan**
Fix for failing duration selector on live streams as well as update to feed link. Current selectors are written for List view.

### CODE REVIEW

**Comment by RunninglVlan** [comment]
Future improvements: You can add "LIVE" instead of empty string for duration element for Live streams (if item.querySelector(".yt-badge-live") is not null for current element).

**Comment by demalexx** [comment]
Thank you for pull request :) I'll take a look soon.

**Comment by demalexx** [comment]
How could I test LIVE videos in subscription? I subscribed to few channels with live videos but I don't see them in my Subscriptions list. Only videos with duration are there. @RunninglVlan

**Comment by demalexx** [comment]
> as well as update to feed link. Current selectors are written for List view.

What do you mean?

**Comment by RunninglVlan** [comment]
> How could I test LIVE videos in subscription?

Well, [this guy](https://www.youtube.com/channel/UCAaegDUlb7doIKo0Rc1F08g) is doing LIVE streams quite often. But the easiest way to test it would be subscribing to someone that is LIVE right now. Youtube has a [playlist](https://www.youtube.com/playlist?list=PLU12uITxBEPHOJO1FU8qll6gQmKcXp5S7) for that.
I just subscribed to 1st channel in the list and 2nd video in my subscribtion list doesn't have duration 'cause it's LIVE right now.


Now about List view. On the previous picture in the upper right corner you can see that List view is selected, right next to it on the left is a Grid view. Now your current selectors are written for List view. Your current link to subscriptions - https://www.youtube.com/feed/subscriptions - will open view that was last used by the user and if it was Grid view, then your current selectors won't work. This link - https://www.youtube.com/feed/subscriptions?flow=2 - opens List view.
So you can either just change current link from https://www.youtube.com/feed/subscriptions to https://www.youtube.com/feed/subscriptions?flow=2 (this won'be be quite user friendly because if user was using Grid view on Youtube, everytime the extension will check this link the view will be changed to List view) or keep the link unchanged, then write a selector which determines which view is used by the user and then decide what selectors to use - either Grid view selectors (which you would need to prepare first) or List view selectors.

**Comment by RunninglVlan** [comment]
Hi, can't you reproduce the issues I fixed with this pull request? I'm still using my patched version of your extension from local environment. I'd rather use extension from Opera repository, but it still has these problems.

**Comment by demalexx** [comment]
Hi! I wrote my own code, it's not only support live videos, but show "Live" text, show scheduled live time and work correctly with both List and Grid layouts. I submitted it yesterday and it's gonna be approved very soon.

Sorry for being too slow :(

**Comment by demalexx** [comment]
It's published. Thanks for your feedback.

**Pull request closed without merging**
