### PR TITLE
Fix for sizing problems

### PR DESCRIPTION
**Pull request by RunninglVlan**
Recently I started using Windows 10 with display resolution 3840x2160 and size of apps: 300%, and your extension has gone bad. It has been enlarged 3 times. I found that it can be fixed by using "size_mode": "adapt" in speeddial element of manifest. Currently default value "auto_zoom" is used.
Here is a screenshot of original extension and updated one with "size_mode": "adapt" on Windows 10:
Windows 10 with display resolution 3840x2160 and size of apps: 300%
And here is a screenshot of original extension and updated one with "size_mode": "adapt" on Windows 7:
Windows 7 with display resolution 1368x768

### CODE REVIEW

**Comment by demalexx** [comment]
Thank you very much for report and fix suggestion!

I also have problems with scaling on Windows 10. Unfortunately as `"size_mode": "adapt"` solves _your_ issue it breaks things on _my_ Windows 10 (FullHD) - I see only one huge preview (like your top-left part from your 1st screenshot). So obviously `size_mode` is not a solution.

This extension does have problems with screen sizes, browser scalings, OS. Frankly these front-end stuff is smth I hate to do. And I don't have all the hardware to test. I'll try to look at this problem but I can't guarantee I'll solve it, or solve it soon.

Thank you again and sorry for very long dealy :3

**Comment by RunninglVlan** [comment]
How does it look like without `"size_mode": "adapt"` for you then? =)
And what are your settings for resolution/zoom?

**Comment by demalexx** [comment]
It looks fine :) I have 1920x1080 Full HD, 150% text size in Windows 10 Control panel. In Opera it's medium font and 110% zoom. After I just switched to Windows 10 I got broken layout (https://forums.opera.com/discussion/1871551/speeddial-extension-scale). Dunno how but then it became ok. So this zoom issue exists and it seems very hard to fix relaibly.

**Comment by demalexx** [comment]
Hey @RunninglVlan, would you like to help me a little? :)

I created debug extension that gets DPI and size of extension thumbnail. It writes it into console. Could you please add it to Opera (drag&drop to Extensions window), press Developer mode button, then press on "Inspect views: index.html" on that debug extension. That'll open dev tools, where you select Concole tab and copy its content to me. That would be helpful. If you could, then screenshot of that debug speed dial would be nice too. And actually I have 2 extensions, one for adapt and other for default size_mode. Output of both extensions would be good. Thanks.

Links: [opera-youtube-adapt.zip](https://github.com/demalexx/youtube-opera-speeddial/files/399042/opera-youtube-adapt.zip), [opera-youtube-default.zip](https://github.com/demalexx/youtube-opera-speeddial/files/399043/opera-youtube-default.zip)

Also you said you have 300% system zoom? I have 175% max, probably because of FullHD monitor.

**Comment by RunninglVlan** [comment]
Right now I use 1920x1080 resolution and 150% zoom on Windows 10.
Extension - adapt:

```
95dpi
96dpi
window.innerWidth 188
window.innerHeight 120
```

Extension - default:

```
102dpi
window.innerWidth 175
window.innerHeight 112
```

Screen
Glad to be of help.

If you want, I could also run tests on Windows 7.

**Comment by demalexx** [comment]
Thanks. Could you please run it on 4k monitor?

**Comment by RunninglVlan** [comment]
For 3840x2160 resolution and 300% zoom only default has changed:

```
205dpi
window.innerWidth 87
window.innerHeight 56
```

Screen

For 3840x2160 resolution and 150% zoom everything was the same.

For 1920x1080 resolution and 175% zoom only default has changed:

```
119dpi
120dpi
window.innerWidth 150
window.innerHeight 96
```

Screen

It looks like only zoom affects the speed dials and adapt can really solve this issue.

**Comment by RunninglVlan** [comment]
Hi, I can't reproduce this issue in the latest Opera, so I guess they fixed this issue.
If you agree, then this pull request can be closed.

**Comment by demalexx** [comment]
Hi, it's very cool it's fixed!

**Pull request closed without merging**
